- Alpha citizens shall have full ownership of their identity.
- One Alpha citizen can only have one identity that is recognised by the ecosystem.
- Alpha citizens own their data and have the possibility to show their data to certain entities if they wish to prove some personal data or statements.
- Alpha citizens can revoke the access to their updated data to any entity at any point in time.
